services:
    nginx:
        image: nginx
        ports: 
            - 80:80
            - 8080:8080
            - 9590:9590
        volumes:
            - ./nginx:/etc/nginx
            - ./www:/usr/b4tut4/www
